config/routes.rb
Rails.application.routes.draw do
  

  resources :messages_from_user
  resources :messages_for_channel
  
  get 'add_user_to_channel/new'
  post 'add_user_to_channel/create'

  get 'channels/new'

  get 'messages/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  
  resources :users 
  resources :channels
  
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  
  has_and_belongs_to_many :users
  
  validates :title, presence: true, length: {maximum: 50}, uniqueness: { case_sensitive: false }

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  
  before_action :logged_in_user

  def new
    @channel = Channel.new
  end
  
  def create
    @channel = Channel.new(channel_params)
    @channel.users << current_user
    if @channel.save
      redirect_to @channel
    else
      render 'new'
    end
  end
  
  def show
    @channel = Channel.find(params[:id])
    @users = @channel.users
    if !@channel.public && !@users.find_by(:id => current_user.id)
      flash[:danger] = "You dont have the acces to this Channel"
      redirect_to current_user
    end
  end

  private
  
   def add_user_to_channel_params
     params.require(:channel).permit(:title, :public)
   end
   
   def channel_params
     params.require(:channel).permit(:title, :public)
   end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/add_user.html.erb
<% provide(:title, 'Add user to channel') %>
<% provide(:button_text, 'Add User') %>
<h1>Add User To <%=@channel.title%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(:channel, url: channels_add_user_to_channel_path) do |f| %>

  <%= hidden_field_tag :id, @channel.id %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
  </div>
</div>

app/views/channels/new.html.erb
<% provide(:title, 'Create new channel') %>
<% provide(:button_text, 'Create new channel') %>
<h1>Create new channel</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@channel) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  
  <%= f.label :public, class: "checkbox inline" do %>
  <%= f.check_box :public %>
    <span>Public Channel</span>
  <% end %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
  </div>
</div>

app/views/channels/show.html.erb
<% provide(:title, @channel.title) %>
<h1><%=@channel.title%></h1>
<%= link_to "Add User", add_user_to_channel_new_path(:id => @channel.id) %> 
<ul class="users">
  <% for user in @users %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for user %>
            <%= user.name %>
          </h1>
        </section>
      </aside>
    </div>
  <%end%>
</ul>